### PR TITLE
Implements water wave

### PR DESCRIPTION
**Pull request by captn3m0**
I don't expect this to be merged, just creating this PR in case someone is interested in using curves instead of bars for visualization.

Visualization demo is at https://www.youtube.com/watch?v=_vWe_AHAJCk

GIF:

output

Would it be worth it to consider "configurable renderers" so that `bars|curves` could be picked?

### CODE REVIEW

**Comment by HaCk3Dq** [comment]
Wow, that's neat, dude

What concerns different renderers: i think they should be implemented in a separate way, some sort of a plugins. Need to architecture them right, to make it more customisable

**Comment by captn3m0** [comment]
Would creating separate `render_{method}` functions be good enough, where method is decided by the config?

**Comment by HaCk3Dq** [comment]
Seems right

**Comment by captn3m0** [comment]
@HaCk3Dq Made the render method configurable via the config and squashed all my commits

**Comment by HaCk3Dq** [comment]
Ty a lot

**Pull request merged**
